id: P593199C1
initial_creation_type: ocr
source_metadata:
  volumes:
    065f46f33bd04b0284fa7ce4d64888ee:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བླ་ན་མེད་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
